
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"

export const GET_PERSON_SUCCESS = "GET_PERSON_SUCCESS"

export const GET_ALL_GENRES_SUCCESS = "GET_ALL_GENRES_SUCCESS"
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS"

export const REMOVE_SELECTED_MOVIE = "REMOVE_SELECTED_MOVIE"